// Italienisch-Vokabeln nach Themen geordnet
// id: eindeutige Nummer, it: italienisch, de: deutsch, cat: Kategorie, gram: Grammatik-Info
const VOCAB = [
  // === Begrüßung & Verabschiedung ===
  { id: 1, it: "Buongiorno!", de: "Guten Tag!", cat: "Begrüßung & Verabschiedung" },
  { id: 2, it: "Buona sera!", de: "Guten Abend!", cat: "Begrüßung & Verabschiedung" },
  { id: 3, it: "Buona notte!", de: "Gute Nacht!", cat: "Begrüßung & Verabschiedung" },
  { id: 4, it: "Sogni d'oro!", de: "Träum schön!", cat: "Begrüßung & Verabschiedung" },
  { id: 5, it: "Ciao!", de: "Hallo!/Tschüss!", cat: "Begrüßung & Verabschiedung" },
  { id: 6, it: "Arrivederci!", de: "Auf Wiedersehen!", cat: "Begrüßung & Verabschiedung" },
  { id: 7, it: "A presto!", de: "Bis bald!", cat: "Begrüßung & Verabschiedung" },
  { id: 8, it: "A dopo!", de: "Bis nachher!", cat: "Begrüßung & Verabschiedung" },
  { id: 9, it: "A domani!", de: "Bis morgen!", cat: "Begrüßung & Verabschiedung" },
  { id: 10, it: "Ci vediamo!", de: "Wir sehen uns!", cat: "Begrüßung & Verabschiedung" },
  { id: 11, it: "Buon fine settimana!", de: "Schönes Wochenende!", cat: "Begrüßung & Verabschiedung" },
  { id: 12, it: "Buona serata!", de: "Schönen Abend noch!", cat: "Begrüßung & Verabschiedung" },
  { id: 13, it: "Buona giornata!", de: "Schönen Tag noch!", cat: "Begrüßung & Verabschiedung" },
  { id: 14, it: "Pronto!", de: "Hallo! (am Telefon)", cat: "Begrüßung & Verabschiedung" },

  // === Sich vorstellen ===
  { id: 20, it: "Mi chiamo...", de: "Ich heiße...", cat: "Sich vorstellen" },
  { id: 21, it: "(io) sono...", de: "Ich bin...", cat: "Sich vorstellen" },
  { id: 22, it: "Il mio nome è...", de: "Mein Name ist...", cat: "Sich vorstellen" },
  { id: 23, it: "Come ti chiami?", de: "Wie heißt du?", cat: "Sich vorstellen" },
  { id: 24, it: "(io) ho dodici anni", de: "Ich bin 12 Jahre alt", cat: "Sich vorstellen", gram: "avere = haben (im IT: 'ich habe 12 Jahre')" },
  { id: 25, it: "Quanti anni hai?", de: "Wie alt bist du?", cat: "Sich vorstellen" },
  { id: 26, it: "(io) abito a...", de: "Ich wohne in...", cat: "Sich vorstellen", gram: "a + Stadt (Vienna, Roma)" },
  { id: 27, it: "Dove abiti?", de: "Wo wohnst du?", cat: "Sich vorstellen" },
  { id: 28, it: "Abito in Austria", de: "Ich wohne in Österreich", cat: "Sich vorstellen", gram: "in + Land (Austria, Italia)" },
  { id: 29, it: "Sono di Padova", de: "Ich stamme aus Padova", cat: "Sich vorstellen", gram: "essere di = stammen von" },
  { id: 30, it: "Piacere!", de: "Angenehm!", cat: "Sich vorstellen" },
  { id: 31, it: "Molto lieto", de: "Sehr erfreut (m)", cat: "Sich vorstellen", gram: "männlich; weiblich: molto lieta" },
  { id: 32, it: "Questo è...", de: "Das ist... (m)", cat: "Sich vorstellen", gram: "männlich (z.B. Marco)" },
  { id: 33, it: "Questa è...", de: "Das ist... (w)", cat: "Sich vorstellen", gram: "weiblich (z.B. Maria)" },
  { id: 34, it: "Sei Marco, vero?", de: "Du bist Marco, nicht wahr?", cat: "Sich vorstellen" },

  // === Gefühle & Befinden ===
  { id: 40, it: "Come stai?", de: "Wie geht es dir?", cat: "Gefühle & Befinden" },
  { id: 41, it: "Come va?", de: "Wie geht's?", cat: "Gefühle & Befinden" },
  { id: 42, it: "(io) sto bene", de: "Mir geht es gut", cat: "Gefühle & Befinden" },
  { id: 43, it: "così così", de: "so lala", cat: "Gefühle & Befinden" },
  { id: 44, it: "male", de: "schlecht", cat: "Gefühle & Befinden" },
  { id: 45, it: "benissimo", de: "sehr gut", cat: "Gefühle & Befinden", gram: "= molto bene" },
  { id: 46, it: "molto bene", de: "sehr gut", cat: "Gefühle & Befinden" },
  { id: 47, it: "malissimo", de: "sehr schlecht", cat: "Gefühle & Befinden", gram: "= molto male" },
  { id: 48, it: "Non c'è male!", de: "Nicht schlecht!", cat: "Gefühle & Befinden" },
  { id: 49, it: "Abbastanza bene", de: "Ziemlich gut", cat: "Gefühle & Befinden" },
  { id: 50, it: "Mi piace", de: "Mir gefällt / Mir schmeckt", cat: "Gefühle & Befinden" },
  { id: 51, it: "Mi piace la pizza", de: "Mir schmeckt die Pizza", cat: "Gefühle & Befinden" },
  { id: 52, it: "Mi piace l'italiano", de: "Mir gefällt Italienisch", cat: "Gefühle & Befinden" },
  { id: 53, it: "Mi dispiace", de: "Es tut mir leid", cat: "Gefühle & Befinden" },

  // === Höflichkeit ===
  { id: 60, it: "per piacere", de: "bitte", cat: "Höflichkeit" },
  { id: 61, it: "per favore", de: "bitte", cat: "Höflichkeit" },
  { id: 62, it: "per cortesia", de: "bitte", cat: "Höflichkeit" },
  { id: 63, it: "prego", de: "Bitte / Hier ist", cat: "Höflichkeit" },
  { id: 64, it: "grazie", de: "danke", cat: "Höflichkeit" },
  { id: 65, it: "grazie mille", de: "tausend Dank", cat: "Höflichkeit" },
  { id: 66, it: "grazie tante", de: "vielen Dank", cat: "Höflichkeit" },
  { id: 67, it: "Grazie, altrettanto", de: "Danke, gleichfalls", cat: "Höflichkeit" },
  { id: 68, it: "Scusa!", de: "Entschuldige!", cat: "Höflichkeit", gram: "informell (du)" },
  { id: 69, it: "Scusi!", de: "Entschuldigen Sie!", cat: "Höflichkeit", gram: "formell (Sie)" },
  { id: 70, it: "Anche a Lei!", de: "Ihnen auch!", cat: "Höflichkeit" },
  { id: 71, it: "E tu?", de: "Und du?", cat: "Höflichkeit" },
  { id: 72, it: "anche", de: "auch", cat: "Höflichkeit" },
  { id: 73, it: "Anch'io!", de: "Ich auch!", cat: "Höflichkeit" },
  { id: 74, it: "e", de: "und", cat: "Höflichkeit" },
  { id: 75, it: "è", de: "er/sie/es ist", cat: "Höflichkeit", gram: "essere = sein" },
  { id: 76, it: "Salute!", de: "Gesundheit!", cat: "Höflichkeit" },
  { id: 77, it: "Buon appetito!", de: "Guten Appetit!", cat: "Höflichkeit" },
  { id: 78, it: "Posso andare in bagno?", de: "Darf ich aufs WC?", cat: "Höflichkeit" },
  { id: 79, it: "Signore", de: "Herr", cat: "Höflichkeit" },
  { id: 80, it: "Signora", de: "Frau", cat: "Höflichkeit" },
  { id: 81, it: "Signor Mazzini", de: "Herr Mazzini", cat: "Höflichkeit", gram: "männlich mit Nachname verliert das 'e'" },
  { id: 82, it: "professore", de: "Professor", cat: "Höflichkeit", gram: "männlich" },
  { id: 83, it: "professoressa", de: "Professorin", cat: "Höflichkeit", gram: "weiblich" },

  // === Wochentage ===
  { id: 90, it: "I giorni della settimana", de: "Die Wochentage", cat: "Wochentage" },
  { id: 91, it: "lunedì", de: "Montag", cat: "Wochentage" },
  { id: 92, it: "martedì", de: "Dienstag", cat: "Wochentage" },
  { id: 93, it: "mercoledì", de: "Mittwoch", cat: "Wochentage" },
  { id: 94, it: "giovedì", de: "Donnerstag", cat: "Wochentage" },
  { id: 95, it: "venerdì", de: "Freitag", cat: "Wochentage" },
  { id: 96, it: "sabato", de: "Samstag", cat: "Wochentage" },
  { id: 97, it: "domenica", de: "Sonntag", cat: "Wochentage" },
  { id: 98, it: "la settimana", de: "die Woche", cat: "Wochentage", gram: "f." },

  // === Monate ===
  { id: 100, it: "il mese", de: "der Monat", cat: "Monate", gram: "m." },
  { id: 101, it: "il gennaio", de: "Jänner", cat: "Monate" },
  { id: 102, it: "il febbraio", de: "Februar", cat: "Monate" },
  { id: 103, it: "il marzo", de: "März", cat: "Monate" },
  { id: 104, it: "l'aprile", de: "April", cat: "Monate" },
  { id: 105, it: "il maggio", de: "Mai", cat: "Monate" },
  { id: 106, it: "il giugno", de: "Juni", cat: "Monate" },
  { id: 107, it: "il luglio", de: "Juli", cat: "Monate" },
  { id: 108, it: "l'agosto", de: "August", cat: "Monate" },
  { id: 109, it: "il settembre", de: "September", cat: "Monate" },
  { id: 110, it: "l'ottobre", de: "Oktober", cat: "Monate" },
  { id: 111, it: "il novembre", de: "November", cat: "Monate" },
  { id: 112, it: "il dicembre", de: "Dezember", cat: "Monate" },
  { id: 113, it: "a settembre", de: "im September", cat: "Monate", gram: "a/in + Monat" },

  // === Verben ===
  { id: 120, it: "lavorare", de: "arbeiten", cat: "Verben" },
  { id: 121, it: "portare", de: "bringen/mitnehmen", cat: "Verben" },
  { id: 122, it: "pagare", de: "bezahlen", cat: "Verben" },
  { id: 123, it: "trovare", de: "finden", cat: "Verben" },
  { id: 124, it: "guardare", de: "(fern)schauen", cat: "Verben", gram: "guardare la TV = fernsehen" },
  { id: 125, it: "cantare", de: "singen", cat: "Verben" },
  { id: 126, it: "avere", de: "haben", cat: "Verben", gram: "ho, hai, ha, abbiamo, avete, hanno" },
  { id: 127, it: "essere", de: "sein", cat: "Verben", gram: "sono, sei, è, siamo, siete, sono" },
  { id: 128, it: "incontrare", de: "treffen", cat: "Verben" },
  { id: 129, it: "andare", de: "gehen/fahren", cat: "Verben", gram: "Ausnahme: vado, vai, va, andiamo, andate, vanno" },
  { id: 130, it: "sentire", de: "hören/fühlen", cat: "Verben" },
  { id: 131, it: "insegnare", de: "lehren/unterrichten", cat: "Verben" },
  { id: 132, it: "sperare che", de: "hoffen, dass / hoffentlich", cat: "Verben" },
  { id: 133, it: "viaggiare", de: "reisen", cat: "Verben" },
  { id: 134, it: "il viaggio", de: "die Reise", cat: "Verben", gram: "m." },
  { id: 135, it: "dire", de: "sagen", cat: "Verben", gram: "dico, dici, ..." },
  { id: 136, it: "seguire", de: "folgen", cat: "Verben" },
  { id: 137, it: "praticare", de: "üben", cat: "Verben" },
  { id: 138, it: "cucinare", de: "kochen", cat: "Verben" },
  { id: 139, it: "la cucina", de: "die Küche", cat: "Verben", gram: "f." },
  { id: 140, it: "visitare", de: "besuchen", cat: "Verben", gram: "z.B. visitare un museo" },
  { id: 141, it: "correre", de: "laufen", cat: "Verben" },

  // === Reflexive Verben ===
  { id: 150, it: "addormentarsi", de: "einschlafen", cat: "Reflexive Verben" },
  { id: 151, it: "alzarsi", de: "aufstehen", cat: "Reflexive Verben" },
  { id: 152, it: "ammalarsi", de: "krank werden", cat: "Reflexive Verben" },
  { id: 153, it: "annoiarsi", de: "sich langweilen", cat: "Reflexive Verben" },
  { id: 154, it: "arrabbiarsi", de: "sich ärgern/wütend werden", cat: "Reflexive Verben" },
  { id: 155, it: "chiamarsi", de: "heißen", cat: "Reflexive Verben" },
  { id: 156, it: "divertirsi", de: "sich amüsieren/Spaß haben", cat: "Reflexive Verben" },
  { id: 157, it: "fermarsi", de: "stehenbleiben", cat: "Reflexive Verben" },
  { id: 158, it: "innamorarsi di", de: "sich verlieben in", cat: "Reflexive Verben" },
  { id: 159, it: "lamentarsi", de: "sich beschweren", cat: "Reflexive Verben" },
  { id: 160, it: "lavarsi", de: "sich waschen", cat: "Reflexive Verben" },
  { id: 161, it: "mettersi", de: "sich anziehen", cat: "Reflexive Verben" },
  { id: 162, it: "pettinarsi", de: "sich kämmen", cat: "Reflexive Verben" },
  { id: 163, it: "preoccuparsi di", de: "sich Sorgen machen um", cat: "Reflexive Verben" },
  { id: 164, it: "prepararsi", de: "sich vorbereiten", cat: "Reflexive Verben" },
  { id: 165, it: "truccarsi", de: "sich schminken", cat: "Reflexive Verben" },
  { id: 166, it: "rilassarsi", de: "sich entspannen", cat: "Reflexive Verben" },
  { id: 167, it: "riposarsi", de: "sich ausruhen", cat: "Reflexive Verben" },
  { id: 168, it: "sedersi", de: "sich setzen", cat: "Reflexive Verben" },
  { id: 169, it: "sentirsi", de: "sich fühlen", cat: "Reflexive Verben" },
  { id: 170, it: "sposarsi", de: "heiraten", cat: "Reflexive Verben" },
  { id: 171, it: "svegliarsi", de: "aufwachen", cat: "Reflexive Verben" },
  { id: 172, it: "trovarsi", de: "sich befinden", cat: "Reflexive Verben" },
  { id: 173, it: "vergognarsi", de: "sich schämen", cat: "Reflexive Verben" },
  { id: 174, it: "vestirsi", de: "sich anziehen", cat: "Reflexive Verben" },

  // === Schule – Fächer & Allgemein ===
  { id: 180, it: "la scuola", de: "die Schule", cat: "Schule", gram: "f." },
  { id: 181, it: "il liceo", de: "das Gymnasium", cat: "Schule", gram: "m." },
  { id: 182, it: "il liceo linguistico", de: "das Sprachengymnasium", cat: "Schule", gram: "m." },
  { id: 183, it: "Vado al liceo BRG Leibnitz nella terza classe", de: "Ich gehe in die 3. Klasse im Gymnasium", cat: "Schule" },
  { id: 184, it: "la materia", de: "das Unterrichtsfach", cat: "Schule", gram: "f." },
  { id: 185, it: "la lezione", de: "die Unterrichtsstunde", cat: "Schule", gram: "f." },
  { id: 186, it: "l'ora", de: "die Stunde", cat: "Schule", gram: "f." },
  { id: 187, it: "l'intervallo", de: "die Pause", cat: "Schule", gram: "m. (auch: la pausa)" },
  { id: 188, it: "la pausa", de: "die Pause", cat: "Schule", gram: "f." },
  { id: 189, it: "l'aula", de: "die Klasse (Raum)", cat: "Schule", gram: "f. (auch: la classe)" },
  { id: 190, it: "la classe", de: "die Klasse", cat: "Schule", gram: "f." },
  { id: 191, it: "la palestra", de: "Turnsaal", cat: "Schule", gram: "f." },
  { id: 192, it: "la piscina", de: "Pool/Schwimmhalle", cat: "Schule", gram: "f." },
  { id: 193, it: "il campo sportivo", de: "Sportplatz", cat: "Schule", gram: "m." },
  { id: 194, it: "l'aula di disegno", de: "Zeichensaal", cat: "Schule", gram: "f." },
  { id: 195, it: "il laboratorio di chimica", de: "Chemielabor", cat: "Schule", gram: "m." },
  { id: 196, it: "la mensa della scuola", de: "Mensa", cat: "Schule", gram: "f." },
  { id: 197, it: "il corridoio", de: "Gang", cat: "Schule", gram: "m." },
  { id: 198, it: "Per (lavorare)", de: "Um zu (arbeiten)", cat: "Schule" },

  // === Schulfächer ===
  { id: 210, it: "l'educazione fisica", de: "Leibeserziehung/Sport", cat: "Schulfächer", gram: "f." },
  { id: 211, it: "la matematica", de: "Mathe", cat: "Schulfächer", gram: "f." },
  { id: 212, it: "l'italiano", de: "Italienisch", cat: "Schulfächer", gram: "m." },
  { id: 213, it: "il tedesco", de: "Deutsch", cat: "Schulfächer", gram: "m." },
  { id: 214, it: "l'inglese", de: "Englisch", cat: "Schulfächer", gram: "m." },
  { id: 215, it: "la biologia", de: "Biologie", cat: "Schulfächer", gram: "f." },
  { id: 216, it: "la fisica", de: "Physik", cat: "Schulfächer", gram: "f." },
  { id: 217, it: "la chimica", de: "Chemie", cat: "Schulfächer", gram: "f." },
  { id: 218, it: "la geografia", de: "Geografie", cat: "Schulfächer", gram: "f." },
  { id: 219, it: "la musica", de: "Musik", cat: "Schulfächer", gram: "f." },
  { id: 220, it: "la religione", de: "Religion", cat: "Schulfächer", gram: "f." },
  { id: 221, it: "l'informatica", de: "Informatik", cat: "Schulfächer", gram: "f." },
  { id: 222, it: "gli studi sociali", de: "Soziales Lernen", cat: "Schulfächer", gram: "m. pl." },
  { id: 223, it: "l'arte", de: "Kunst", cat: "Schulfächer", gram: "f." },
  { id: 224, it: "la storia", de: "Geschichte", cat: "Schulfächer", gram: "f." },

  // === Schulsachen ===
  { id: 230, it: "la penna", de: "der Stift", cat: "Schulsachen", gram: "f." },
  { id: 231, it: "la colla", de: "Kleber", cat: "Schulsachen", gram: "f." },
  { id: 232, it: "la gomma", de: "Radiergummi", cat: "Schulsachen", gram: "f." },
  { id: 233, it: "la matita", de: "Bleistift", cat: "Schulsachen", gram: "f." },
  { id: 234, it: "il cellulare", de: "Handy", cat: "Schulsachen", gram: "m. (auch: il telefono)" },
  { id: 235, it: "il telefono", de: "Telefon", cat: "Schulsachen", gram: "m." },
  { id: 236, it: "il raccoglitore", de: "Mappe", cat: "Schulsachen", gram: "m." },
  { id: 237, it: "l'astuccio", de: "Federpenal", cat: "Schulsachen", gram: "m." },
  { id: 238, it: "il test", de: "der Test", cat: "Schulsachen", gram: "m." },
  { id: 239, it: "il testo", de: "Text", cat: "Schulsachen", gram: "m." },
  { id: 240, it: "il compito in classe", de: "Schularbeit", cat: "Schulsachen", gram: "m." },
  { id: 241, it: "il compito per casa", de: "Hausübung", cat: "Schulsachen", gram: "m." },
  { id: 242, it: "l'esercizio", de: "Übung", cat: "Schulsachen", gram: "m. (auch: il compito)" },
  { id: 243, it: "la parola", de: "Wort", cat: "Schulsachen", gram: "f." },
  { id: 244, it: "la frase", de: "Satz", cat: "Schulsachen", gram: "f." },

  // === Freunde & Personen ===
  { id: 250, it: "amico", de: "Freund", cat: "Freunde & Personen", gram: "m. sg." },
  { id: 251, it: "amica", de: "Freundin", cat: "Freunde & Personen", gram: "f. sg." },
  { id: 252, it: "amici", de: "Freunde", cat: "Freunde & Personen", gram: "m. pl." },
  { id: 253, it: "amiche", de: "Freundinnen", cat: "Freunde & Personen", gram: "f. pl." },
  { id: 254, it: "la testa", de: "Kopf", cat: "Freunde & Personen", gram: "f." },
  { id: 255, it: "la/le foto", de: "Foto/s", cat: "Freunde & Personen", gram: "abgekürzt von 'fotografia'" },
  { id: 256, it: "caro/cara", de: "Lieber/Liebe", cat: "Freunde & Personen", gram: "m./f." },
  { id: 257, it: "bacio", de: "Kuss", cat: "Freunde & Personen", gram: "m." },
  { id: 258, it: "baciare", de: "küssen", cat: "Freunde & Personen" },
  { id: 259, it: "abbraccio", de: "Umarmung", cat: "Freunde & Personen", gram: "m." },

  // === Ausgehen ===
  { id: 270, it: "volentieri", de: "gerne", cat: "Ausgehen & Restaurant" },
  { id: 271, it: "in pizzeria", de: "in der Pizzeria", cat: "Ausgehen & Restaurant" },
  { id: 272, it: "al bar", de: "in der Bar/im Kaffeehaus", cat: "Ausgehen & Restaurant" },
  { id: 273, it: "al ristorante", de: "im Restaurant", cat: "Ausgehen & Restaurant" },
  { id: 274, it: "in gelateria", de: "in der Eisdiele", cat: "Ausgehen & Restaurant" },
  { id: 275, it: "Dimmi!", de: "Sag mir!", cat: "Ausgehen & Restaurant" },
  { id: 276, it: "da bere", de: "zu trinken", cat: "Ausgehen & Restaurant" },
  { id: 277, it: "da mangiare", de: "zu essen", cat: "Ausgehen & Restaurant" },
  { id: 278, it: "Che gusti?", de: "Welche Geschmäcker?", cat: "Ausgehen & Restaurant" },
  { id: 279, it: "Il conto, per favore", de: "Die Rechnung, bitte!", cat: "Ausgehen & Restaurant" },

  // === Adjektive ===
  { id: 290, it: "simpatico", de: "sympathisch", cat: "Adjektive" },
  { id: 291, it: "antipatico", de: "unsympathisch", cat: "Adjektive" },
  { id: 292, it: "allegro", de: "fröhlich", cat: "Adjektive" },
  { id: 293, it: "triste", de: "traurig", cat: "Adjektive" },
  { id: 294, it: "vivace", de: "lebhaft", cat: "Adjektive" },
  { id: 295, it: "timido", de: "schüchtern", cat: "Adjektive" },
  { id: 296, it: "intelligente", de: "intelligent", cat: "Adjektive" },
  { id: 297, it: "furbo", de: "schlau", cat: "Adjektive" },
  { id: 298, it: "stupido", de: "dumm", cat: "Adjektive" },
  { id: 299, it: "scemo", de: "blöd", cat: "Adjektive" },
  { id: 300, it: "interessante", de: "interessant", cat: "Adjektive" },
  { id: 301, it: "noioso", de: "langweilig", cat: "Adjektive" },
  { id: 302, it: "alto", de: "hoch/groß", cat: "Adjektive" },
  { id: 303, it: "basso", de: "niedrig/klein", cat: "Adjektive" },
  { id: 304, it: "grande", de: "groß", cat: "Adjektive" },
  { id: 305, it: "piccolo", de: "klein", cat: "Adjektive" },
  { id: 306, it: "forte", de: "stark", cat: "Adjektive" },
  { id: 307, it: "debole", de: "schwach", cat: "Adjektive" },
  { id: 308, it: "giovane", de: "jung", cat: "Adjektive" },
  { id: 309, it: "anziano", de: "alt (Person)", cat: "Adjektive" },
  { id: 310, it: "nuovo", de: "neu", cat: "Adjektive" },
  { id: 311, it: "vecchio", de: "alt", cat: "Adjektive" },
  { id: 312, it: "moderno", de: "modern", cat: "Adjektive" },
  { id: 313, it: "antico", de: "alt (Sache)", cat: "Adjektive", gram: "auch: antiquato" },
  { id: 314, it: "elegante", de: "elegant", cat: "Adjektive" },
  { id: 315, it: "sportivo", de: "sportlich", cat: "Adjektive" },
  { id: 316, it: "bello", de: "schön", cat: "Adjektive" },
  { id: 317, it: "brutto", de: "hässlich", cat: "Adjektive" },
  { id: 318, it: "difficile", de: "schwer", cat: "Adjektive" },
  { id: 319, it: "facile", de: "leicht", cat: "Adjektive" },
  { id: 320, it: "lungo", de: "lang", cat: "Adjektive" },
  { id: 321, it: "breve", de: "kurz", cat: "Adjektive", gram: "auch: corto" },
  { id: 322, it: "veloce", de: "schnell", cat: "Adjektive", gram: "auch: rapido" },
  { id: 323, it: "lento", de: "langsam", cat: "Adjektive" },
  { id: 324, it: "ricco", de: "reich", cat: "Adjektive" },
  { id: 325, it: "povero", de: "arm", cat: "Adjektive" },
  { id: 326, it: "chiaro", de: "hell", cat: "Adjektive" },
  { id: 327, it: "scuro", de: "dunkel", cat: "Adjektive" },
  { id: 328, it: "gentile", de: "nett/freundlich", cat: "Adjektive", gram: "auch: amichevole" },
  { id: 329, it: "cortese", de: "höflich", cat: "Adjektive" },
  { id: 330, it: "scortese", de: "unhöflich", cat: "Adjektive" },
  { id: 331, it: "occupato", de: "besetzt", cat: "Adjektive" },
  { id: 332, it: "libero", de: "frei", cat: "Adjektive" },
  { id: 333, it: "dolce", de: "süß", cat: "Adjektive" },
  { id: 334, it: "amaro", de: "bitter", cat: "Adjektive" },
  { id: 335, it: "acido", de: "sauer", cat: "Adjektive" },
  { id: 336, it: "grosso", de: "dick/fett", cat: "Adjektive", gram: "auch: magro = dünn" },
  { id: 337, it: "magro", de: "mager/dünn", cat: "Adjektive", gram: "auch: snello" },
  { id: 338, it: "pulito", de: "sauber", cat: "Adjektive" },
  { id: 339, it: "sporco", de: "schmutzig", cat: "Adjektive" },
  { id: 340, it: "economico", de: "billig", cat: "Adjektive" },
  { id: 341, it: "caro", de: "teuer", cat: "Adjektive", gram: "auch: costoso" },
  { id: 342, it: "caldo", de: "warm", cat: "Adjektive" },
  { id: 343, it: "freddo", de: "kalt", cat: "Adjektive" },

  // === Freizeit & Sport ===
  { id: 360, it: "nel tempo libero", de: "in der Freizeit", cat: "Freizeit & Sport" },
  { id: 361, it: "l'attività", de: "die Aktivität", cat: "Freizeit & Sport", gram: "f." },
  { id: 362, it: "l'allenamento", de: "das Training", cat: "Freizeit & Sport", gram: "m." },
  { id: 363, it: "lo spettacolo", de: "die Aufführung", cat: "Freizeit & Sport", gram: "m." },
  { id: 364, it: "vietato", de: "verboten", cat: "Freizeit & Sport" },
  { id: 365, it: "Peccato!", de: "Schade!", cat: "Freizeit & Sport" },
  { id: 366, it: "fuori", de: "draußen", cat: "Freizeit & Sport" },
  { id: 367, it: "la caramella", de: "Süßigkeiten/Zuckerl", cat: "Freizeit & Sport", gram: "f." },
  { id: 368, it: "pattinare", de: "eislaufen", cat: "Freizeit & Sport" },
  { id: 369, it: "l'auto", de: "das Auto", cat: "Freizeit & Sport", gram: "f. (auch: la macchina)" },
  { id: 370, it: "la macchina", de: "das Auto", cat: "Freizeit & Sport", gram: "f." },

  // === Musikinstrumente ===
  { id: 380, it: "suonare uno strumento", de: "ein Instrument spielen", cat: "Musik & Instrumente" },
  { id: 381, it: "la chitarra", de: "Gitarre", cat: "Musik & Instrumente", gram: "f." },
  { id: 382, it: "la tromba", de: "Trompete", cat: "Musik & Instrumente", gram: "f." },
  { id: 383, it: "il sassofono", de: "Saxophon", cat: "Musik & Instrumente", gram: "m." },
  { id: 384, it: "il violino", de: "Geige", cat: "Musik & Instrumente", gram: "m." },
  { id: 385, it: "il pianoforte", de: "Klavier", cat: "Musik & Instrumente", gram: "m." },
  { id: 386, it: "il flauto", de: "Flöte", cat: "Musik & Instrumente", gram: "m." },
  { id: 387, it: "la batteria", de: "Schlagzeug", cat: "Musik & Instrumente", gram: "f." },

  // === Sportarten ===
  { id: 400, it: "giocare a calcio", de: "Fußball spielen", cat: "Sportarten" },
  { id: 401, it: "giocare a pallavolo", de: "Volleyball spielen", cat: "Sportarten" },
  { id: 402, it: "giocare a pallacanestro", de: "Basketball spielen", cat: "Sportarten", gram: "auch: basket" },
  { id: 403, it: "giocare a tennis", de: "Tennis spielen", cat: "Sportarten" },
  { id: 404, it: "il pattinaggio", de: "Eislaufen", cat: "Sportarten", gram: "m." },
  { id: 405, it: "lo sci", de: "Schi", cat: "Sportarten", gram: "m." },
  { id: 406, it: "sciare", de: "schifahren", cat: "Sportarten" },
  { id: 407, it: "il nuoto", de: "Schwimmsport", cat: "Sportarten", gram: "m." },
  { id: 408, it: "nuotare", de: "schwimmen", cat: "Sportarten" },
  { id: 409, it: "andare in bici", de: "Radfahren", cat: "Sportarten" },
  { id: 410, it: "mountain bike", de: "Mountainbike", cat: "Sportarten" },
  { id: 411, it: "andare a cavallo", de: "reiten", cat: "Sportarten", gram: "auch: cavalcare" },
  { id: 412, it: "cavalcare", de: "reiten", cat: "Sportarten" },

  // === Kleine Wörter & Sonstiges ===
  { id: 430, it: "poco", de: "wenig", cat: "Kleine Wörter & Sonstiges", gram: "Plural: pochi" },
  { id: 431, it: "quello", de: "jener", cat: "Kleine Wörter & Sonstiges" },
  { id: 432, it: "solo", de: "allein/nur", cat: "Kleine Wörter & Sonstiges", gram: "z.B. ho solo 10€" },
  { id: 433, it: "non...nemmeno", de: "nicht einmal", cat: "Kleine Wörter & Sonstiges" },
  { id: 434, it: "nella prima ora", de: "in der 1. Stunde", cat: "Kleine Wörter & Sonstiges" },
  { id: 435, it: "nella seconda ora", de: "in der 2. Stunde", cat: "Kleine Wörter & Sonstiges" },
  { id: 436, it: "nella terza ora", de: "in der 3. Stunde", cat: "Kleine Wörter & Sonstiges" },
  { id: 437, it: "nella quarta ora", de: "in der 4. Stunde", cat: "Kleine Wörter & Sonstiges" },
  { id: 438, it: "nella quinta ora", de: "in der 5. Stunde", cat: "Kleine Wörter & Sonstiges" },
  { id: 439, it: "nella sesta ora", de: "in der 6. Stunde", cat: "Kleine Wörter & Sonstiges" }
];
